name: Just Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        $solution = Get-ChildItem -Recurse -Filter "*.sln" | Select-Object -First 1
        # Билдим проект
        msbuild $solution.FullName /p:Configuration=Release /p:Platform=x64

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: my-cheat-dll
        # Путь берем из твоего лога: Cheat-Base/_output/
        path: "**/_output/*.dll"
