name: Just Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        $solution = Get-ChildItem -Recurse -Filter "*.sln" | Select-Object -First 1
        msbuild $solution.FullName /p:Configuration=Release /p:Platform=x64
